default_stages: [commit]
repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.77.0
      hooks:
        - id: terraform_fmt
        - id: terraform_tflint
        - id: terraform_tfsec
          args:
            - '--args=--exclude-downloaded-modules'
        - id: terraform_checkov

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-toml
        - id: check-xml
        - id: check-merge-conflict
        - id: pretty-format-json
          args: [--autofix]
        - id: check-symlinks
        - id: detect-private-key

    - repo: https://github.com/homebysix/pre-commit-macadmin
      rev: v1.12.3
      hooks:
        - id: check-git-config-email
          args: ['--domains', 'sonnleitner.cl']

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.28.0
      hooks:
        - id: yamllint
          args: ['--no-warnings', '-d', 'relaxed', '.']
          files: ^\.terraform/

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.38.0
      hooks:
        - id: commitizen
        - id: commitizen-branch
          stages: [push]

    - repo: https://github.com/thoughtworks/talisman
      rev: 'v1.29.4'  # Update me!
      hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
